const NAME = 'NAME';
const FNAME = 'FNAME';
const MNAME = 'MNAME'
const CITY = 'CITY'
const STATE = 'STATE'
const GENDER = 'GENDER'
const AREA = 'AREA'
const PHOTO = 'PHOTO'
const CNAME = 'CNAME'
const CCITY = 'CCITY'
const CSTATE = 'CSTATE'
const SYLLABUS = 'SYLLABUS'
const SUBJECT = 'SUBJECT'
const GRADE = 'GRADE'
const PERCENT = 'PERCENT'
const COURSE = 'COURSE'
const AGREE = 'AGREE'

export { NAME, FNAME, MNAME, CITY, STATE, GENDER, AREA, PHOTO, CNAME, CCITY, CSTATE, SUBJECT, SYLLABUS, GRADE, PERCENT, COURSE, AGREE };